-- Raw vs DWH counts
SELECT COUNT(*) AS raw_events FROM RETAIL.RAW.ORDER_STATUS_EVENTS;
SELECT COUNT(*) AS dwh_orders FROM RETAIL.DWH.ORDER_STATUS;

-- Freshness
SELECT MAX(LAST_UPDATE_TS) AS dwh_last_update FROM RETAIL.DWH.ORDER_STATUS;

-- Status distribution
SELECT CURRENT_STATUS, COUNT(*)
FROM RETAIL.DWH.ORDER_STATUS
GROUP BY 1
ORDER BY 2 DESC;

-- DWH order ids must exist in RAW.ORDER (if loaded)
SELECT COUNT(*) AS missing_in_raw_orders
FROM RETAIL.DWH.ORDER_STATUS d
LEFT JOIN RETAIL.RAW."ORDER" o ON o.ORDER_ID = d.ORDER_ID
WHERE o.ORDER_ID IS NULL;

-- Latest event per order agrees with DWH
WITH latest AS (
  SELECT ORDER_ID, NEW_STATUS,
         ROW_NUMBER() OVER (PARTITION BY ORDER_ID ORDER BY STATUS_TS DESC) rn
  FROM RETAIL.RAW.EVENTS
)
SELECT COUNT(*) AS mismatches
FROM latest l
JOIN RETAIL.DWH.ORDER_STATUS d USING (ORDER_ID)
WHERE l.rn = 1 AND l.NEW_STATUS <> d.CURRENT_STATUS;

